# Generated by Django 2.2.6 on 2021-04-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('author',), 'verbose_name': 'Подписан'},
        ),
    ]
